### ISSUE TITLE
Create a git branch for ImGui's docking branch

### ISSUE THREAD

**Issue by floooh** [fips-libs/fips-imgui#5]
...so that it would be possible to use ImGui's docking branch like this (in fips.yml):

```yaml
imports:
    git: https://github.com/fips-libs/fips-imgui
    branch: docking
```
